<?php

namespace David\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsoleRepository extends EntityRepository
{
}
