services:
    sonata.admin.game:
        class: David\GameBundle\Admin\GameAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Game" }
        arguments:
            - ~
            - David\GameBundle\Entity\Game
            - ~
        calls:
            - [ setTranslationDomain, [DavidGameBundle]]